### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by cainwatson** [JustDrawIt/drawit#194]

**Comment by natastro** [comment]
Happy to help with Spanish translations if needed!

**Comment by cainwatson** [comment]
Thanks for offering @natastro! I don't have a timeline on when this will get started, but if you'd like to, you can start by adding the Spanish translations of the random words in here: https://github.com/JustDrawIt/drawit/tree/main/server/apps/draw_it/lib/draw_it/random_words

I imagine this might need to be much more verbose, but for now, you could create a `easy-es.json` file and translate the words in the order they are in the `easy.json`. There's a ton of words in there, so don't feel like you have to do all of them! Let me know if you have any questions or concerns.

**Comment by natastro** [comment]
Wonderful, thank you @cainwatson ! I'll get started on these 😄

**Comment by natastro** [comment]
Hi again @cainwatson ! I'm working on the easy.json file and have some questions and notes

For the words below, I need some assistance on the context of the words as they can have multiple translations.
- bow: as in a bow and arrow or like a hairbow?
- branch: this one is a tree branch, correct?
- float: swim float? or the verb, to float?
- fly: the insect, a zipper, or the verb to fly?
- hook: hanging pictures, hanging clothes, or a fish hook?
- lock: is this a padlock or just a locking mechanism?
- nail: fingernail or nail for construction?
- outlet: electric outlet or outlet mall?
- speaker: as in the person or to play audio?
_(sorry for questioning all of these, just want to make sure you have the right translations)_

There are two sets of words that have the same spanish translations since they have the same meaning:
avion - airplane + plane
barco - ship + boat

Please let me know if you have any questions! Thank you!

**Comment by cainwatson** [comment]
Hi @natastro, thanks for being so thorough!

When I pulled the words, a lot of them were not necessarily tangible things or easy to draw and I tried to remove as many as I could that wouldn't be fun to play with. (Also, I realize this is pretty subjective as to what is "easy" to draw, but alas.)

With that in mind, let's go with these definitions:

- bow: hairbow
- branch: tree branch
- float: as in a float in a parade
- fly: insect
- hook: fishhook
- lock: padlock
- nail: construction
- outlet: electric
- speaker: play audio

As for the ones with the same meaning, I think it would be best to just remove the synonyms. Thinking we could keep "airplane" over "plane", and keep "boat" over "ship".
